'''
Snakemake workflow for phylogenetic analysis
Assignment 5 - BIOL-6101

Refer to the README.md for detailed instructions.
'''

# Load configuration
configfile: 'config/config.yaml'


# Rule all: define the final outputs of the workflow
rule all:
    input:
        # Define all final output files here
